### ISSUE TITLE
Intro to git

### ISSUE THREAD

**Issue by hatidzhe** [hatidzhe/administration#5]

**Comment by elsamuko** [comment]
Learn the following terms:
git commit
git status
git log
git pull
git push
git checkout
git merge

Answer these question:
What is origin?
What is stage?
How do you see changes?
What's a suitable GUI for git?

More Infos:
https://training.github.com/kit/downloads/github-git-cheat-sheet.pdf
http://cheat.errtheblog.com/s/git

**Comment by hatidzhe** [comment]
Some Terms and Their Features

git commit -m "[descriptive message]"
Records file snapshots permanently in version history

git status
Lists all new or modified files to be committed

git log
Lists version history for the current branch

git pull
Downloads bookmark history and incorporates changes

git push [alias] [branch]
Uploads all local branch commits to GitHub

git checkout [branch-name]
Switches to the specified branch and updates the working directory

git merge [branch]
Combines the specified branch’s history into the current branch

**Comment by hatidzhe** [comment]
Answer to the questions above:
What is origin?

How do you see changes? --> git pull

What's a suitable GUI for git?--> File Manager PCManFM

**Comment by hatidzhe** [comment]
How to commit changes?
1. Create a file or make a change in already existing file with nano <filename> or touch <filename> .
2. Stage the file with git add <filename> .
3. Commit with git commit -m "chg: note" .
4. Push with git push origin master.

How to remove a file?
git rm <filename>. With this command you should not to stage the changes, but your next step is directly to commit and then to push the commit.
With rm <filename> you sholud use git add after the command rm <filename> .
