### ISSUE TITLE
Intro to Markdown

### ISSUE THREAD

**Issue by elsamuko** [hatidzhe/administration#7]
- What is markdown (https://help.github.com/articles/github-flavored-markdown/)
- Change the README.md in a text editor, commit and push it

**Comment by hatidzhe** [comment]
- What is markdown: allows you to write using an easy-to-read, easy-to-write plain text format, which then converts to valid HTML for viewing on GitHub

**Comment by hatidzhe** [comment]
- important links:  (https://guides.github.com/features/mastering-markdown/)
                          (https://help.github.com/articles/markdown-basics/)
